Test.name("Better AA main menu production AA")
local q = Test.mod.extension("ReduxBetterAA.Quality")
local original = q.settings()
local function capture(label, count)
    q.capture(label,count)
    Test.wait["until"](function() return q.ready() end, 60)
end
local function run()
    Test.game.wait_for_state("MainMenu",45)
    Test.render.wait_stable(60)
    q.menu_freeze(true)
    for _, mode in ipairs({"Off","FXAA High","SMAA","TAA","NVIDIA DLAA","FSR 2 Native AA"}) do
        q.set({_modeEntry=mode,_sharpnessEntry=0,_dlaaPresetEntry="M"})
        Test.render.wait_stable(120)
        local state=q.menu_snapshot()
        local label=string.gsub(mode,"[^%w]","")
        local expected=mode=="TAA" and "Custom TAA" or (mode=="FSR 2 Native AA" and "FSR2 Native AA" or mode)
        Test.assert.equal(state.selected,expected,"Selected backend executes")
        Test.assert.true_(state.jitter,"Recognized menu stack supports jitter")
        Test.assert.true_(state.transparent_jitter,"Menu includes transparent projection jitter")
        Test.report.value(label,state)
        if mode=="Off" or mode=="FXAA High" or mode=="SMAA" then
            q.menu_reference(1)
            capture(label,2)
            q.menu_reference_stop()
        else
            Test.assert.true_(state.active,"Temporal backend active")
            capture(label,8)
            q.profile_start()
            Test.wait["until"](function() return q.profile_ready() end, 60)
            Test.report.value(label.."-profile",q.profile())
        end
        Test.capture.screenshot(label,{hideUI=true,waitFrames=2})
    end
    q.set({_modeEntry="Off"})
    Test.render.wait_stable(15)
    q.menu_reference(2)
    Test.render.wait_stable(8)
    capture("reference",1)
    q.menu_reference_stop()
    Test.wait.frames(8)
    for cycle=1,3 do
        for _, mode in ipairs({"TAA","NVIDIA DLAA","FSR 2 Native AA","Off"}) do
            q.set({_modeEntry=mode})
            Test.render.wait_stable(20)
            if mode=="Off" then Test.assert.equal(q.menu_snapshot().owned_bytes,0,"Off releases menu histories and contexts") end
        end
    end
    q.menu_freeze(false)
    q.set({_modeEntry="NVIDIA DLAA"})
    Test.render.wait_stable(60)
    capture("animated-DLAA",8)
    Test.capture.screenshot("menu-ui",{hideUI=false,waitFrames=2})
    q.menu_resize(1920,1080)
    Test.wait["until"](function() return q.menu_snapshot().width==1920 end,15)
    Test.render.wait_stable(60)
    capture("resized-DLAA",2)
    q.menu_resize()
    Test.render.wait_stable(60)
    capture("restored-DLAA",2)
    Test.game.load_save("local/launchpad-fly-safe-15")
    Test.game.wait_for_state("Flight",45)
    Test.flight.start("Fly Safe-15")
    Test.game.pause()
    for _, mode in ipairs({"TAA","NVIDIA DLAA","FSR 2 Native AA"}) do
        q.set({_modeEntry=mode})
        Test.render.wait_stable(60)
        Test.assert.true_(q.menu_snapshot().jitter,"Flight retains jitter")
        Test.assert.false_(q.menu_snapshot().transparent_jitter,"Flight transparent policy unchanged")
        capture("flight-"..string.gsub(mode,"[^%w]",""),1)
    end
    local aa=Test.mod.extension("ReduxBetterAA")
    q.set({_mapViewAaEntry=true})
    aa.open_map_view()
    Test.game.wait_for_state("Map3DView",30)
    Test.render.wait_stable(60)
    Test.assert.false_(q.menu_snapshot().jitter,"Map retains zero-jitter policy")
    Test.assert.false_(q.menu_snapshot().transparent_jitter,"Map transparent policy unchanged")
    capture("map-FSR2",1)
    Test.assert.true_(q.return_menu(),"Normal game shutdown flow starts")
    Test.game.wait_for_state("MainMenu",45)
    Test.render.wait_stable(180)
    for _, mode in ipairs({"TAA","NVIDIA DLAA","FSR 2 Native AA"}) do
        q.set({_modeEntry=mode})
        Test.render.wait_stable(90)
        Test.assert.true_(q.menu_snapshot().jitter,"Menu jitter reacquired after gameplay")
        Test.assert.true_(q.menu_snapshot().transparent_jitter,"Menu transparent jitter reacquired")
        capture("returned-"..string.gsub(mode,"[^%w]",""),2)
    end
end
local ok,err=pcall(run)
q.menu_reference_stop()
q.menu_resize()
q.menu_freeze(false)
q.set(original)
if not ok then error(err) end
