Test.name("DLAA cloud guard causal isolation - TEST ONLY")
local aa = Test.mod.extension("ReduxBetterAA")
local beta = Test.mod.extension("ReduxBetterAA.Beta")
local original = beta.settings()
local function capture(label)
    local before = beta.snapshot()
    Test.report.value(label .. "-before", before)
    Test.report.value(label .. "-cloud", aa.dlaa_cloud_transition_snapshot())
    Test.assert.true_(beta.report(), "Buffer report accepted: " .. label)
    Test.wait["until"](function() return not beta.snapshot().report_busy end, 180)
    Test.report.value("buffers-" .. label, beta.snapshot().report_zip)
    Test.report.value(label .. "-after", beta.snapshot())
    if before.selected == "NVIDIA DLAA" then
        Test.assert.greater(beta.snapshot().temporal_input_captures, before.temporal_input_captures,
            "True DLAA input captured")
    end
end
local ok, err = pcall(function()
    beta.set_settings({_modeEntry="Off", _sharpnessEntry=0, _dlaaPresetEntry="M"})
    Test.game.load_save("local/launchpad-fly-safe-15")
    Test.game.wait_for_state("Flight", 60)
    Test.flight.start("Fly Safe-15")
    Test.game.pause()
    Test.camera.mode("Flight")
    Test.camera.target_vessel()
    Test.camera.orbit {distance=45, yaw=30, pitch=35, fov=55}
    Test.render.wait_stable(120)
    capture("flight-Off-guard-control")
    beta.set_settings({_modeEntry="NVIDIA DLAA"})
    Test.render.wait_stable(240)
    capture("flight-DLAA-production-guard")
    beta.set_settings({_modeEntry="Off"})
    beta.set_cloud_guard_suppressed(true)
    beta.set_settings({_modeEntry="NVIDIA DLAA"})
    Test.render.wait_stable(240)
    capture("flight-DLAA-guard-suppressed-TEST-ONLY")
end)
beta.set_settings({_modeEntry="Off"})
beta.set_cloud_guard_suppressed(false)
beta.set_settings(original)
if not ok then error(err) end
Test.report.note("Cloud guard suppression is a temporary diagnostic override, not a production fix or cloud-quality validation. No stock cloud state is altered by the override.")
