Test.name("DLAA reinstall: actual same-frame resolve versus no AA")
local aa = Test.mod.extension("ReduxBetterAA")
local beta = Test.mod.extension("ReduxBetterAA.Beta")
Test.assert.not_equal(beta, nil, "Visual adapter installed")
local original = beta.settings()
local function capture(label)
    local before = beta.snapshot()
    Test.report.value(label .. "-before", beta.snapshot())
    Test.report.value(label .. "-cloud", aa.dlaa_cloud_transition_snapshot())
    Test.assert.true_(beta.report(), "Buffer report accepted: " .. label)
    Test.wait["until"](function() return not beta.snapshot().report_busy end, 180)
    Test.report.value("buffers-" .. label, beta.snapshot().report_zip)
    Test.report.value(label .. "-after", beta.snapshot())
    if before.selected == "NVIDIA DLAA" then
        Test.assert.greater(beta.snapshot().temporal_input_captures, before.temporal_input_captures,
            "True backend input captured before DLAA: " .. label)
    end
end
local ok, err = pcall(function()
    beta.set_settings({_modeEntry="Off", _sharpnessEntry=0})
    Test.render.wait_stable(120)
    capture("menu-Off")
    beta.set_settings({_modeEntry="NVIDIA DLAA", _sharpnessEntry=0, _dlaaPresetEntry="M"})
    Test.render.wait_stable(180)
    capture("menu-DLAA")
    beta.set_settings({_modeEntry="Off"})
    Test.game.load_save("local/launchpad-fly-safe-15")
    Test.game.wait_for_state("Flight", 60)
    Test.flight.start("Fly Safe-15")
    Test.game.pause()
    Test.camera.mode("Flight")
    Test.camera.target_vessel()
    Test.camera.orbit {distance=45, yaw=0, pitch=35, fov=55}
    Test.render.wait_stable(180)
    capture("flight-Off")
    beta.set_settings({_modeEntry="NVIDIA DLAA", _sharpnessEntry=0})
    Test.render.wait_stable(240)
    capture("flight-DLAA")
    Test.camera.orbit {distance=45, yaw=30, pitch=35, fov=55}
    Test.render.wait_stable(240)
    capture("flight-DLAA-rotated")
    beta.set_settings({_modeEntry="Off"})
    Test.render.wait_stable(120)
    capture("flight-Off-rotated")
    Test.game.unpause()
    beta.set_settings({_modeEntry="NVIDIA DLAA"})
    Test.render.wait_stable(360)
    capture("flight-DLAA-unpaused")
    beta.set_settings({_modeEntry="Off"})
    Test.render.set("clouds", false)
    Test.render.wait_stable(180)
    capture("flight-Off-clouds-disabled")
    beta.set_settings({_modeEntry="NVIDIA DLAA"})
    Test.render.wait_stable(240)
    capture("flight-DLAA-clouds-disabled")
    beta.set_settings({_modeEntry="Off"})
    Test.render.set("clouds", true)
    Test.game.pause()
    Test.render.wait_stable(120)
    capture("flight-Off-guard-control")
    beta.set_cloud_guard_suppressed(true)
    beta.set_settings({_modeEntry="NVIDIA DLAA"})
    Test.render.wait_stable(240)
    capture("flight-DLAA-guard-suppressed-TEST-ONLY")
end)
beta.panel(false)
beta.set_settings({_modeEntry="Off"})
beta.set_cloud_guard_suppressed(false)
beta.set_settings(original)
if not ok then error(err) end
Test.report.note("Compare scene-input and scene-output within each report, then compare the same camera pose across true Off and DLAA. Sharpness is zero; cloud guard state is recorded. Different sequential frames alone do not prove AA.")
