Test.name("Better AA: native settings UI with DLAA")
local beta = Test.mod.extension("ReduxBetterAA.Beta")
Test.assert.not_equal(beta, nil, "Install the test-only visual adapter")
local original = beta.settings()
local ok, err = pcall(function()
    Test.game.wait_for_state("MainMenu", 60)
    Test.wait["until"](function() return beta.settings_menu_ready() end, 30)
    Test.assert.true_(beta.settings_ui(true), "Native Redux settings page is visible")
    Test.wait["until"](function() return beta.settings_ui_ready() end, 30)
    beta.settings_ui_set("Mode", "NVIDIA DLAA")
    beta.settings_ui_set("DLAA preset", "M")
    for _, ticks in ipairs({15, 0, 100}) do
        beta.settings_ui_set("Sharpness", ticks)
        Test.render.wait_stable(90)
        local state = beta.snapshot()
        Test.assert.equal(state.selected, "NVIDIA DLAA", "DLAA selected through the native dropdown")
        Test.assert.true_(state.active, "DLAA is active, without fallback")
        Test.assert.near(state.sharpness, ticks / 100, 0.00001, "Native slider reaches the backend")
        Test.assert.equal(beta.settings()._dlaaPresetEntry, "M", "Native preset dropdown reaches configuration")
        local label = string.format("settings-dlaa-sharpness-%03d", ticks)
        Test.report.value(label, state)
        Test.capture.screenshot(label, {hideUI = false, waitFrames = 2})
    end
end)
beta.settings_ui(false)
beta.set_settings(original)
if not ok then error(err) end
Test.report.note("Three native Settings > Mods > Redux Better AA screenshots. DLAA M only; sharpness 0.15, 0 and 1. Original settings restored. Manual layout review required.")
