Test.name("Better AA: native settings UI with DLAA")
local beta = Test.mod.extension("ReduxBetterAA.Beta")
Test.assert.not_equal(beta, nil, "Install the test-only visual adapter")
local original = beta.settings()
local ok, err = pcall(function()
    Test.game.wait_for_state("MainMenu", 60)
    Test.wait["until"](function() return beta.settings_menu_ready() end, 30)
    Test.assert.true_(beta.settings_ui(true), "Native Redux settings page is visible")
    Test.wait["until"](function() return beta.settings_ui_ready() end, 30)
    beta.settings_ui(true, "graphics")
    Test.render.wait_stable(30)
    local stock = beta.stock_controls()
    Test.report.value("stock-controls", stock)
    Test.assert.true_(stock.aa_disabled, "Stock AA control redirected")
    Test.assert.true_(stock.supersampling_disabled, "Stock supersampling control redirected")
    Test.capture.screenshot("settings-stock-graphics", {hideUI=false,waitFrames=2})
    beta.settings_ui(true)
    Test.wait["until"](function() return beta.settings_ui_ready() end, 30)
    beta.settings_ui_set("Mode", "Supersampling")
    beta.settings_ui_set("Supersampling scale", "150")
    Test.wait["until"](function() return string.find(beta.snapshot().status, "fallback") ~= nil end, 10)
    local ss = beta.snapshot()
    Test.report.value("menu-supersampling", ss)
    Test.assert.equal(ss.requested, "Supersampling", "Native mode dropdown saves supersampling")
    Test.assert.equal(ss.selected, "Off", "Menu without a stock presenter reports Off fallback")
    Test.assert.equal(beta.settings()._supersamplingEntry, 150, "Native dropdown saves scale")
    Test.capture.screenshot("settings-supersampling", {hideUI=false,waitFrames=2})
    beta.settings_ui_set("Mode", "Off")
    Test.render.wait_stable(15)
    local off = beta.snapshot()
    Test.assert.equal(off.scene_width, off.screen_width, "Off restores native menu rendering")
    Test.assert.equal(off.owned_targets, 0, "Off owns no temporal targets")
    beta.settings_ui_set("Mode", "NVIDIA DLAA")
    beta.settings_ui_set("DLAA preset", "M")
    for _, ticks in ipairs({15, 0, 100}) do
        beta.settings_ui_set("Sharpness", ticks)
        Test.render.wait_stable(90)
        local state = beta.snapshot()
        Test.assert.equal(state.selected, "NVIDIA DLAA", "DLAA selected through the native dropdown")
        Test.assert.true_(state.active, "DLAA is active, without fallback")
        Test.assert.near(state.sharpness, ticks / 100, 0.00001, "Native slider reaches the backend")
        Test.assert.equal(beta.settings()._dlaaPresetEntry, "M", "Native preset dropdown reaches configuration")
        local label = string.format("settings-dlaa-sharpness-%03d", ticks)
        Test.report.value(label, state)
        Test.capture.screenshot(label, {hideUI = false, waitFrames = 2})
    end
end)
beta.settings_ui(false)
beta.set_settings(original)
if not ok then error(err) end
Test.report.note("Three native Settings > Mods > Redux Better AA screenshots. DLAA M only; sharpness 0.15, 0 and 1. Original settings restored. Manual layout review required.")
