Test.name("Consecutive asynchronous motion/camera/physics cadence probe")
local q=Test.mod.extension("ReduxBetterAA.Motion")
Test.game.load_save("local/launchpad-fly-safe-15")
Test.game.wait_for_state("Flight",60)
Test.flight.start("Fly Safe-15")
Test.camera.mode("Flight")
Test.camera.target_vessel()
Test.camera.orbit {distance=45,yaw=20,pitch=20,fov=55}
q.fps(120)
q.set("NVIDIA DLAA")
Test.game.pause()
Test.render.wait_stable(120)
Test.assert.equal(q.selected(),"NVIDIA DLAA","Requested backend active")
q.start("stationary-dlaa",240)
Test.wait["until"](function() return q.ready() end,90)
Test.game.unpause()
Test.flight.set_sas(true)
Test.flight.set_throttle(1.0)
Test.flight.stage()
Test.wait.seconds(5)
q.start("launch-slow-dlaa",360)
Test.wait["until"](function() return q.ready() end,90)
Test.wait.seconds(12)
q.start("late-flight-dlaa",600)
Test.wait["until"](function() return q.ready() end,90)
Test.report.value("vessel",Test.flight.active_vessel())
Test.capture.screenshot("late-flight",{scale=1,hideUI=false,waitFrames=0})
Test.report.note("Staging this fixture may deploy a parachute. Inspect camera travel and measured speed; the later interval is not assumed to be fast flight.")
