Test.name("Launchpad image scouting with native camera control released")
local q=Test.mod.extension("ReduxBetterAA.Motion")
Test.game.load_save("local/launchpad-fly-safe-15")
Test.game.wait_for_state("Flight",60)
Test.flight.start("Fly Safe-15")
Test.game.pause()
Test.camera.mode("Flight")
Test.camera.orbit {distance=60,yaw=45,pitch=45,fov=55}
Test.camera.release()
q.fps(120)
q.set("NVIDIA DLAA")
Test.render.wait_stable(120)
q.audit("flight-auto")
q.start("scout-paused",60,true,true)
Test.wait["until"](function() return q.ready() end,90)
Test.capture.screenshot("launchpad-paused",{scale=1,hideUI=true,waitFrames=0})
Test.game.unpause()
q.start("scout-live",120,true,true)
Test.wait["until"](function() return q.ready() end,90)
Test.flight.set_sas(true)
Test.flight.set_throttle(1)
Test.flight.stage()
Test.wait.frames(15)
q.start("scout-launch",240,true,true)
Test.wait["until"](function() return q.ready() end,90)
Test.capture.screenshot("launchpad-liftoff",{scale=1,hideUI=true,waitFrames=0})
Test.game.pause()
Test.camera.mode("Cinematic")
Test.render.wait_stable(30)
q.audit("flight-cinematic")
